"""
config_ufs.py
Configuracao por UF para o scraper de deputados estaduais.

Cada entrada contem:
  - url: pagina com lista de deputados
  - tipo: "api_json" | "html" | "api_xml"
  - seletor_lista: CSS selector para os cards de deputado (quando HTML)
  - seletor_nome, seletor_partido, seletor_email: CSS selectors
  - api_url, api_path: para UFs com API (ALMG)
  - notas: peculiaridades conhecidas

Para UFs com "STATUS: pendente", o scraper generico retorna lista vazia e
imprime um aviso. Voce refina cada UF conforme valida em producao.
"""

UFS_CONFIG = {
    "AC": {
        "assembleia": "ALEAC",
        "url": "https://www.aleac.net.br/deputados/",
        "tipo": "html",
        "seletor_lista": ".deputado-card",
        "seletor_nome": ".nome",
        "seletor_partido": ".partido",
        "status": "pendente",
    },
    "AL": {
        "assembleia": "ALE-AL",
        "url": "https://www.al.al.leg.br/deputados",
        "tipo": "html",
        "seletor_lista": ".view-content .views-row",
        "seletor_nome": "h3",
        "seletor_partido": ".partido",
        "status": "pendente",
    },
    "AM": {
        "assembleia": "ALEAM",
        "url": "https://www.ale.am.gov.br/deputados/",
        "tipo": "html",
        "seletor_lista": ".deputado",
        "seletor_nome": ".nome",
        "seletor_partido": ".partido",
        "status": "pendente",
    },
    "AP": {
        "assembleia": "ALAP",
        "url": "https://al.ap.leg.br/pagina.php?pg=exibir_depestaduais",
        "tipo": "html",
        "seletor_lista": ".deputado",
        "seletor_nome": ".nome",
        "seletor_partido": ".partido",
        "status": "pendente",
    },
    "BA": {
        "assembleia": "ALBA",
        "url": "https://www.al.ba.leg.br/deputados",
        "tipo": "html",
        "seletor_lista": ".deputado",
        "seletor_nome": ".nome",
        "seletor_partido": ".partido",
        "status": "pendente",
    },
    "CE": {
        "assembleia": "ALECE",
        "url": "https://www2.al.ce.gov.br/legislativo/deputados.htm",
        "tipo": "html",
        "seletor_lista": "table tr",
        "seletor_nome": "td:nth-child(1)",
        "seletor_partido": "td:nth-child(2)",
        "status": "pendente",
    },
    "DF": {
        "assembleia": "CLDF",
        "url": "https://www.cl.df.gov.br/deputados",
        "tipo": "html",
        "seletor_lista": ".deputado-card",
        "seletor_nome": ".nome",
        "seletor_partido": ".partido",
        "status": "pendente",
        "notas": "Na verdade e Camara Legislativa do DF, nao Assembleia.",
    },
    "ES": {
        "assembleia": "ALES",
        "url": "https://www.al.es.gov.br/Deputado",
        "tipo": "html",
        "seletor_lista": ".deputado-card, .card",
        "seletor_nome": ".nome, h3",
        "seletor_partido": ".partido",
        "status": "pendente",
    },
    "GO": {
        "assembleia": "ALEGO",
        "url": "https://portal.al.go.leg.br/deputados",
        "tipo": "html",
        "seletor_lista": ".deputado",
        "seletor_nome": ".nome",
        "seletor_partido": ".partido",
        "status": "pendente",
    },
    "MA": {
        "assembleia": "ALEMA",
        "url": "https://www.al.ma.leg.br/deputados",
        "tipo": "html",
        "seletor_lista": ".deputado",
        "seletor_nome": ".nome",
        "seletor_partido": ".partido",
        "status": "pendente",
    },
    "MG": {
        "assembleia": "ALMG",
        "url": "https://dadosabertos.almg.gov.br/ws/deputados/em_exercicio?formato=json",
        "tipo": "api_json",
        "api_path": ["list_deputado", "deputado"],
        "mapa_campos": {"nome": "nome", "partido": "partido", "email": "email"},
        "status": "ok",
        "notas": "ALMG tem dados abertos reais. Ponto forte.",
    },
    "MS": {
        "assembleia": "ALEMS",
        "url": "https://www.al.ms.gov.br/Deputados",
        "tipo": "html",
        "seletor_lista": ".deputado",
        "seletor_nome": ".nome",
        "seletor_partido": ".partido",
        "status": "pendente",
    },
    "MT": {
        "assembleia": "ALMT",
        "url": "https://www.al.mt.gov.br/deputados",
        "tipo": "html",
        "seletor_lista": ".deputado",
        "seletor_nome": ".nome",
        "seletor_partido": ".partido",
        "status": "pendente",
    },
    "PA": {
        "assembleia": "ALEPA",
        "url": "https://www.alepa.pa.gov.br/deputados",
        "tipo": "html",
        "seletor_lista": ".deputado",
        "seletor_nome": ".nome",
        "seletor_partido": ".partido",
        "status": "pendente",
    },
    "PB": {
        "assembleia": "ALPB",
        "url": "https://www.al.pb.leg.br/deputado",
        "tipo": "html",
        "seletor_lista": ".deputado",
        "seletor_nome": ".nome",
        "seletor_partido": ".partido",
        "status": "pendente",
        "notas": "Estado do Philipe (PB). Prioridade alta.",
    },
    "PE": {
        "assembleia": "ALEPE",
        "url": "https://www.alepe.pe.gov.br/deputados/",
        "tipo": "html",
        "seletor_lista": ".deputado",
        "seletor_nome": ".nome",
        "seletor_partido": ".partido",
        "status": "pendente",
    },
    "PI": {
        "assembleia": "ALEPI",
        "url": "https://www.al.pi.leg.br/deputados",
        "tipo": "html",
        "seletor_lista": ".deputado",
        "seletor_nome": ".nome",
        "seletor_partido": ".partido",
        "status": "pendente",
    },
    "PR": {
        "assembleia": "ALEP",
        "url": "https://www.assembleia.pr.leg.br/deputados",
        "tipo": "html",
        "seletor_lista": ".deputado",
        "seletor_nome": ".nome",
        "seletor_partido": ".partido",
        "status": "pendente",
    },
    "RJ": {
        "assembleia": "ALERJ",
        "url": "https://www.alerj.rj.gov.br/Visualizar/Deputados",
        "tipo": "html",
        "seletor_lista": ".deputado",
        "seletor_nome": ".nome",
        "seletor_partido": ".partido",
        "status": "pendente",
    },
    "RN": {
        "assembleia": "ALRN",
        "url": "https://www.al.rn.leg.br/portal/deputados",
        "tipo": "html",
        "seletor_lista": ".deputado",
        "seletor_nome": ".nome",
        "seletor_partido": ".partido",
        "status": "pendente",
    },
    "RO": {
        "assembleia": "ALE-RO",
        "url": "https://www.al.ro.leg.br/deputados",
        "tipo": "html",
        "seletor_lista": ".deputado",
        "seletor_nome": ".nome",
        "seletor_partido": ".partido",
        "status": "pendente",
    },
    "RR": {
        "assembleia": "ALE-RR",
        "url": "https://www.al.rr.leg.br/deputados",
        "tipo": "html",
        "seletor_lista": ".deputado",
        "seletor_nome": ".nome",
        "seletor_partido": ".partido",
        "status": "pendente",
    },
    "RS": {
        "assembleia": "AL-RS",
        "url": "https://www.al.rs.gov.br/agenciaal/deputados",
        "tipo": "html",
        "seletor_lista": ".deputado",
        "seletor_nome": ".nome",
        "seletor_partido": ".partido",
        "status": "pendente",
    },
    "SC": {
        "assembleia": "ALESC",
        "url": "https://www.alesc.sc.gov.br/deputados",
        "tipo": "html",
        "seletor_lista": ".deputado",
        "seletor_nome": ".nome",
        "seletor_partido": ".partido",
        "status": "pendente",
    },
    "SE": {
        "assembleia": "ALESE",
        "url": "https://www.al.se.leg.br/deputados/",
        "tipo": "html",
        "seletor_lista": ".deputado",
        "seletor_nome": ".nome",
        "seletor_partido": ".partido",
        "status": "pendente",
    },
    "SP": {
        "assembleia": "ALESP",
        "url": "https://www.al.sp.gov.br/alesp/deputados/",
        "tipo": "html",
        "seletor_lista": ".deputado, .card-deputado",
        "seletor_nome": ".nome, h3",
        "seletor_partido": ".partido",
        "status": "pendente",
        "notas": "Maior bancada (94). Prioridade alta.",
    },
    "TO": {
        "assembleia": "ALETO",
        "url": "https://www.al.to.leg.br/deputados",
        "tipo": "html",
        "seletor_lista": ".deputado",
        "seletor_nome": ".nome",
        "seletor_partido": ".partido",
        "status": "pendente",
    },
}
